-- SPDX-License-Identifier: AGPL-3.0-or-later
/-
Generated by scripts/gen_keywords.py from the Pancake lexers of the pinned revisions.
Do not edit by hand.
-/
namespace DN.Compiler.Keywords

/-- The words `get_keyword_def` turns into keywords, per pinned revision. Words with a
leading `@` and the empty string are left out: the identifier rule rejects them by shape. -/
def byRevision : List (String × List String) :=
  [("e8eca63affd1653105ca4b9cc2f5ca87a01cd0af",
    ["skip", "st", "stw", "st8", "st16", "st32", "if", "else", "while", "break", "continue",
     "throw", "return", "tick", "var", "in", "try", "catch", "lds", "ldw", "ld8", "ld16",
     "ld32", "true", "false", "fun", "export", "inline", "exception", "struct"]),
   ("ed31510b3b0d0523283b68ef7066882526d77df9",
    ["skip", "st", "stw", "st8", "st16", "st32", "if", "else", "while", "break", "continue",
     "raise", "return", "tick", "var", "in", "with", "handle", "lds", "ldw", "ld8", "ld16",
     "ld32", "true", "false", "fun", "export", "inline", "struct"])]

/-- Every word that is a keyword at some pinned revision. -/
def all : List String := (byRevision.flatMap Prod.snd).eraseDups

end DN.Compiler.Keywords
