-- SPDX-License-Identifier: AGPL-3.0-or-later

/-!
# DN.Server.Layout

Where the server program keeps what it exchanges with its host, as offsets from `@base`, and the
codes of the events and actions (docs/decisions/0003-nntp-slice.md). The program is written from
these numbers and `dn-compiler emit-layout` prints them as a C header for the host, so the two
cannot disagree about them.

The first 64 bytes of the heap are left to the header the host writes before the program starts
(native/cake_header.c): no area of the layout reaches into them, and the checking host sees the
header intact on every call. Every offset is a multiple of eight, so a word lies on a word boundary
whenever `@base` does.
-/

namespace DN.Server.Layout

/-- The version of this layout, which each call hands the host. -/
def version : Nat := 1

/-- Events or actions in one batch. -/
def batch : Nat := 16

/-- Data bytes in one event or action. -/
def data : Nat := 512

/-- The configuration bytes of both calls: the version word. -/
def confOff : Nat := 64
def confLen : Nat := 8

/-- An event: kind, connection index, generation, data length, then the data. -/
def eventHead : Nat := 32
def eventSlot : Nat := eventHead + data

/-- The array `dn_next` fills: the number of events, the host's clock in milliseconds, then the
events. -/
def nextOff : Nat := 128
def nextLen : Nat := 16 + batch * eventSlot

/-- An action: kind, connection index, generation, data length, whether to read from the
connection afterwards, how many bytes the host sent (written back by the host), then the data. -/
def actionHead : Nat := 48
def actionSlot : Nat := actionHead + data

/-- The array `dn_emit` hands over: the number of actions, the earliest deadline in the host's
clock (zero for none), then the actions. -/
def emitOff : Nat := nextOff + nextLen
def emitLen : Nat := 16 + batch * actionSlot

/-- The bytes of heap the program needs from `@base`. -/
def size : Nat := emitOff + emitLen

/-- Event kinds. -/
def opened : Nat := 1
def received : Nat := 2
def writable : Nat := 3
def inputEnded : Nat := 4
def closed : Nat := 5

/-- Action kinds. -/
def send : Nat := 1
def closeAfterSend : Nat := 2
def closeNow : Nat := 3

/-- The names of the two external calls. -/
def nextName : String := "dn_next"
def emitName : String := "dn_emit"

/-- The layout as a C header. -/
def header : String :=
  let defs : List (String × Nat) :=
    [("VERSION", version), ("BATCH", batch), ("DATA", data), ("CONF_OFF", confOff),
     ("CONF_LEN", confLen), ("EVENT_HEAD", eventHead), ("EVENT_SLOT", eventSlot),
     ("NEXT_OFF", nextOff), ("NEXT_LEN", nextLen), ("ACTION_HEAD", actionHead),
     ("ACTION_SLOT", actionSlot), ("EMIT_OFF", emitOff), ("EMIT_LEN", emitLen), ("SIZE", size),
     ("OPENED", opened), ("RECEIVED", received), ("WRITABLE", writable),
     ("INPUT_ENDED", inputEnded), ("CLOSED", closed), ("SEND", send),
     ("CLOSE_AFTER_SEND", closeAfterSend), ("CLOSE_NOW", closeNow)]
  "/* Generated by dn-compiler emit-layout from DN.Server.Layout. */\n" ++
  "#ifndef DN_LAYOUT_H\n#define DN_LAYOUT_H\n" ++
  String.join (defs.map fun (name, value) => s!"#define DN_LAYOUT_{name} {value}\n") ++
  "#endif\n"

/-- The areas stay clear of the header, do not overlap, and each word of them is aligned. -/
theorem areas_disjoint :
    64 ≤ confOff ∧ confOff + confLen ≤ nextOff ∧ nextOff + nextLen ≤ emitOff := by decide

theorem offsets_aligned :
    confOff % 8 = 0 ∧ nextOff % 8 = 0 ∧ emitOff % 8 = 0 ∧ eventSlot % 8 = 0 ∧
      actionSlot % 8 = 0 := by decide

end DN.Server.Layout
