/* GENERATED by build-cake-lib.sh — do not edit.
   32 symbol-disjoint per-shard images of the export-function serve, so
   that many shards run the serve in parallel over private heaps. */
#define CAKE_IMAGE_COUNT 32
extern void *cake0_cml_heap, *cake0_cml_stack, *cake0_cml_stackend;
extern void cake0_cml_main(void);
extern uint64_t cake0_serve(uint64_t,uint64_t,uint64_t,uint64_t);
extern void *cake1_cml_heap, *cake1_cml_stack, *cake1_cml_stackend;
extern void cake1_cml_main(void);
extern uint64_t cake1_serve(uint64_t,uint64_t,uint64_t,uint64_t);
extern void *cake2_cml_heap, *cake2_cml_stack, *cake2_cml_stackend;
extern void cake2_cml_main(void);
extern uint64_t cake2_serve(uint64_t,uint64_t,uint64_t,uint64_t);
extern void *cake3_cml_heap, *cake3_cml_stack, *cake3_cml_stackend;
extern void cake3_cml_main(void);
extern uint64_t cake3_serve(uint64_t,uint64_t,uint64_t,uint64_t);
extern void *cake4_cml_heap, *cake4_cml_stack, *cake4_cml_stackend;
extern void cake4_cml_main(void);
extern uint64_t cake4_serve(uint64_t,uint64_t,uint64_t,uint64_t);
extern void *cake5_cml_heap, *cake5_cml_stack, *cake5_cml_stackend;
extern void cake5_cml_main(void);
extern uint64_t cake5_serve(uint64_t,uint64_t,uint64_t,uint64_t);
extern void *cake6_cml_heap, *cake6_cml_stack, *cake6_cml_stackend;
extern void cake6_cml_main(void);
extern uint64_t cake6_serve(uint64_t,uint64_t,uint64_t,uint64_t);
extern void *cake7_cml_heap, *cake7_cml_stack, *cake7_cml_stackend;
extern void cake7_cml_main(void);
extern uint64_t cake7_serve(uint64_t,uint64_t,uint64_t,uint64_t);
extern void *cake8_cml_heap, *cake8_cml_stack, *cake8_cml_stackend;
extern void cake8_cml_main(void);
extern uint64_t cake8_serve(uint64_t,uint64_t,uint64_t,uint64_t);
extern void *cake9_cml_heap, *cake9_cml_stack, *cake9_cml_stackend;
extern void cake9_cml_main(void);
extern uint64_t cake9_serve(uint64_t,uint64_t,uint64_t,uint64_t);
extern void *cake10_cml_heap, *cake10_cml_stack, *cake10_cml_stackend;
extern void cake10_cml_main(void);
extern uint64_t cake10_serve(uint64_t,uint64_t,uint64_t,uint64_t);
extern void *cake11_cml_heap, *cake11_cml_stack, *cake11_cml_stackend;
extern void cake11_cml_main(void);
extern uint64_t cake11_serve(uint64_t,uint64_t,uint64_t,uint64_t);
extern void *cake12_cml_heap, *cake12_cml_stack, *cake12_cml_stackend;
extern void cake12_cml_main(void);
extern uint64_t cake12_serve(uint64_t,uint64_t,uint64_t,uint64_t);
extern void *cake13_cml_heap, *cake13_cml_stack, *cake13_cml_stackend;
extern void cake13_cml_main(void);
extern uint64_t cake13_serve(uint64_t,uint64_t,uint64_t,uint64_t);
extern void *cake14_cml_heap, *cake14_cml_stack, *cake14_cml_stackend;
extern void cake14_cml_main(void);
extern uint64_t cake14_serve(uint64_t,uint64_t,uint64_t,uint64_t);
extern void *cake15_cml_heap, *cake15_cml_stack, *cake15_cml_stackend;
extern void cake15_cml_main(void);
extern uint64_t cake15_serve(uint64_t,uint64_t,uint64_t,uint64_t);
extern void *cake16_cml_heap, *cake16_cml_stack, *cake16_cml_stackend;
extern void cake16_cml_main(void);
extern uint64_t cake16_serve(uint64_t,uint64_t,uint64_t,uint64_t);
extern void *cake17_cml_heap, *cake17_cml_stack, *cake17_cml_stackend;
extern void cake17_cml_main(void);
extern uint64_t cake17_serve(uint64_t,uint64_t,uint64_t,uint64_t);
extern void *cake18_cml_heap, *cake18_cml_stack, *cake18_cml_stackend;
extern void cake18_cml_main(void);
extern uint64_t cake18_serve(uint64_t,uint64_t,uint64_t,uint64_t);
extern void *cake19_cml_heap, *cake19_cml_stack, *cake19_cml_stackend;
extern void cake19_cml_main(void);
extern uint64_t cake19_serve(uint64_t,uint64_t,uint64_t,uint64_t);
extern void *cake20_cml_heap, *cake20_cml_stack, *cake20_cml_stackend;
extern void cake20_cml_main(void);
extern uint64_t cake20_serve(uint64_t,uint64_t,uint64_t,uint64_t);
extern void *cake21_cml_heap, *cake21_cml_stack, *cake21_cml_stackend;
extern void cake21_cml_main(void);
extern uint64_t cake21_serve(uint64_t,uint64_t,uint64_t,uint64_t);
extern void *cake22_cml_heap, *cake22_cml_stack, *cake22_cml_stackend;
extern void cake22_cml_main(void);
extern uint64_t cake22_serve(uint64_t,uint64_t,uint64_t,uint64_t);
extern void *cake23_cml_heap, *cake23_cml_stack, *cake23_cml_stackend;
extern void cake23_cml_main(void);
extern uint64_t cake23_serve(uint64_t,uint64_t,uint64_t,uint64_t);
extern void *cake24_cml_heap, *cake24_cml_stack, *cake24_cml_stackend;
extern void cake24_cml_main(void);
extern uint64_t cake24_serve(uint64_t,uint64_t,uint64_t,uint64_t);
extern void *cake25_cml_heap, *cake25_cml_stack, *cake25_cml_stackend;
extern void cake25_cml_main(void);
extern uint64_t cake25_serve(uint64_t,uint64_t,uint64_t,uint64_t);
extern void *cake26_cml_heap, *cake26_cml_stack, *cake26_cml_stackend;
extern void cake26_cml_main(void);
extern uint64_t cake26_serve(uint64_t,uint64_t,uint64_t,uint64_t);
extern void *cake27_cml_heap, *cake27_cml_stack, *cake27_cml_stackend;
extern void cake27_cml_main(void);
extern uint64_t cake27_serve(uint64_t,uint64_t,uint64_t,uint64_t);
extern void *cake28_cml_heap, *cake28_cml_stack, *cake28_cml_stackend;
extern void cake28_cml_main(void);
extern uint64_t cake28_serve(uint64_t,uint64_t,uint64_t,uint64_t);
extern void *cake29_cml_heap, *cake29_cml_stack, *cake29_cml_stackend;
extern void cake29_cml_main(void);
extern uint64_t cake29_serve(uint64_t,uint64_t,uint64_t,uint64_t);
extern void *cake30_cml_heap, *cake30_cml_stack, *cake30_cml_stackend;
extern void cake30_cml_main(void);
extern uint64_t cake30_serve(uint64_t,uint64_t,uint64_t,uint64_t);
extern void *cake31_cml_heap, *cake31_cml_stack, *cake31_cml_stackend;
extern void cake31_cml_main(void);
extern uint64_t cake31_serve(uint64_t,uint64_t,uint64_t,uint64_t);
static void **const cake_heap_slot[CAKE_IMAGE_COUNT] = {
  &cake0_cml_heap,
  &cake1_cml_heap,
  &cake2_cml_heap,
  &cake3_cml_heap,
  &cake4_cml_heap,
  &cake5_cml_heap,
  &cake6_cml_heap,
  &cake7_cml_heap,
  &cake8_cml_heap,
  &cake9_cml_heap,
  &cake10_cml_heap,
  &cake11_cml_heap,
  &cake12_cml_heap,
  &cake13_cml_heap,
  &cake14_cml_heap,
  &cake15_cml_heap,
  &cake16_cml_heap,
  &cake17_cml_heap,
  &cake18_cml_heap,
  &cake19_cml_heap,
  &cake20_cml_heap,
  &cake21_cml_heap,
  &cake22_cml_heap,
  &cake23_cml_heap,
  &cake24_cml_heap,
  &cake25_cml_heap,
  &cake26_cml_heap,
  &cake27_cml_heap,
  &cake28_cml_heap,
  &cake29_cml_heap,
  &cake30_cml_heap,
  &cake31_cml_heap,
};
static void **const cake_stack_slot[CAKE_IMAGE_COUNT] = {
  &cake0_cml_stack,
  &cake1_cml_stack,
  &cake2_cml_stack,
  &cake3_cml_stack,
  &cake4_cml_stack,
  &cake5_cml_stack,
  &cake6_cml_stack,
  &cake7_cml_stack,
  &cake8_cml_stack,
  &cake9_cml_stack,
  &cake10_cml_stack,
  &cake11_cml_stack,
  &cake12_cml_stack,
  &cake13_cml_stack,
  &cake14_cml_stack,
  &cake15_cml_stack,
  &cake16_cml_stack,
  &cake17_cml_stack,
  &cake18_cml_stack,
  &cake19_cml_stack,
  &cake20_cml_stack,
  &cake21_cml_stack,
  &cake22_cml_stack,
  &cake23_cml_stack,
  &cake24_cml_stack,
  &cake25_cml_stack,
  &cake26_cml_stack,
  &cake27_cml_stack,
  &cake28_cml_stack,
  &cake29_cml_stack,
  &cake30_cml_stack,
  &cake31_cml_stack,
};
static void **const cake_stackend_slot[CAKE_IMAGE_COUNT] = {
  &cake0_cml_stackend,
  &cake1_cml_stackend,
  &cake2_cml_stackend,
  &cake3_cml_stackend,
  &cake4_cml_stackend,
  &cake5_cml_stackend,
  &cake6_cml_stackend,
  &cake7_cml_stackend,
  &cake8_cml_stackend,
  &cake9_cml_stackend,
  &cake10_cml_stackend,
  &cake11_cml_stackend,
  &cake12_cml_stackend,
  &cake13_cml_stackend,
  &cake14_cml_stackend,
  &cake15_cml_stackend,
  &cake16_cml_stackend,
  &cake17_cml_stackend,
  &cake18_cml_stackend,
  &cake19_cml_stackend,
  &cake20_cml_stackend,
  &cake21_cml_stackend,
  &cake22_cml_stackend,
  &cake23_cml_stackend,
  &cake24_cml_stackend,
  &cake25_cml_stackend,
  &cake26_cml_stackend,
  &cake27_cml_stackend,
  &cake28_cml_stackend,
  &cake29_cml_stackend,
  &cake30_cml_stackend,
  &cake31_cml_stackend,
};
static void (*const cake_init_fn[CAKE_IMAGE_COUNT])(void) = {
  cake0_cml_main,
  cake1_cml_main,
  cake2_cml_main,
  cake3_cml_main,
  cake4_cml_main,
  cake5_cml_main,
  cake6_cml_main,
  cake7_cml_main,
  cake8_cml_main,
  cake9_cml_main,
  cake10_cml_main,
  cake11_cml_main,
  cake12_cml_main,
  cake13_cml_main,
  cake14_cml_main,
  cake15_cml_main,
  cake16_cml_main,
  cake17_cml_main,
  cake18_cml_main,
  cake19_cml_main,
  cake20_cml_main,
  cake21_cml_main,
  cake22_cml_main,
  cake23_cml_main,
  cake24_cml_main,
  cake25_cml_main,
  cake26_cml_main,
  cake27_cml_main,
  cake28_cml_main,
  cake29_cml_main,
  cake30_cml_main,
  cake31_cml_main,
};
static uint64_t (*const cake_serve_fn[CAKE_IMAGE_COUNT])(uint64_t,uint64_t,uint64_t,uint64_t) = {
  cake0_serve,
  cake1_serve,
  cake2_serve,
  cake3_serve,
  cake4_serve,
  cake5_serve,
  cake6_serve,
  cake7_serve,
  cake8_serve,
  cake9_serve,
  cake10_serve,
  cake11_serve,
  cake12_serve,
  cake13_serve,
  cake14_serve,
  cake15_serve,
  cake16_serve,
  cake17_serve,
  cake18_serve,
  cake19_serve,
  cake20_serve,
  cake21_serve,
  cake22_serve,
  cake23_serve,
  cake24_serve,
  cake25_serve,
  cake26_serve,
  cake27_serve,
  cake28_serve,
  cake29_serve,
  cake30_serve,
  cake31_serve,
};
