/* SPDX-License-Identifier: AGPL-3.0-or-later
 * What the hosts of the entry benchmark share (scripts/entry_bench.py), on top of host.h: failing
 * with a reason, bounded numbers, the clock, and the check that an array the program hands the host
 * lies in its heap. entry_layout.h is generated by that script. */
#ifndef DN_ENTRY_H
#define DN_ENTRY_H
#define _GNU_SOURCE
#include "cake_runtime.h"
#include "entry_layout.h"
#include "host.h"
#include <inttypes.h>
#include <time.h>

/* The external functions the loop programs call; the generated code calls them as C functions. */
void ffidn_config(unsigned char *c, long clen, unsigned char *a, long alen);
void ffidn_nop(unsigned char *c, long clen, unsigned char *a, long alen);
void ffidn_next(unsigned char *c, long clen, unsigned char *a, long alen);
void ffidn_emit(unsigned char *c, long clen, unsigned char *a, long alen);

/* The program or the server under test did what it must not. */
__attribute__((noreturn)) static inline void dn_fail(const char *what) { dn_violation("entry: %s", what); }

/* The host cannot go on. */
__attribute__((noreturn)) static inline void dn_broken(const char *what) { dn_harness("entry: %s", what); }

__attribute__((noreturn)) static inline void dn_broken_errno(const char *what) {
    dn_harness("entry: %s: %s", what, strerror(errno));
}

/* A decimal number from `low` to `high`, or the host ends. */
static inline long dn_number(const char *text, long low, long high) {
    uint64_t value = dn_parse_u64(text, (uint64_t)high);
    if (value < (uint64_t)low) dn_harness("entry: %s is below %ld", text, low);
    return (long)value;
}

static inline double dn_now_ns(void) {
    struct timespec t;
    clock_gettime(CLOCK_MONOTONIC, &t);
    return (double)t.tv_sec * 1e9 + (double)t.tv_nsec;
}

/* The theorem's domain is the heap from @base to @top, below the globals; these programs declare
   none, so it is the heap the runtime provisioned. */
static inline void dn_in_heap(const unsigned char *p, long len, const char *what) {
    uintptr_t start = (uintptr_t)cml_heap, end = start + DN_RUNTIME_SEGMENT_BYTES, at = (uintptr_t)p;
    if (len < 0 || at < start || at > end || (uintptr_t)len > end - at)
        dn_violation("entry: %s: %ld bytes at %#" PRIxPTR " lie outside the heap [%#" PRIxPTR ", %#"
                     PRIxPTR ")", what, len, at, start, end);
}

/* Everything in the heap past the header and outside the two batch areas is filled before a
   hostile or checked run and has to be untouched after it. The fill reads as a slot with a small
   length, so a program that strays out of its batch area finds plausible work there and gives
   itself away by answering it. */
#define DN_ENTRY_FILL_WORD UINT64_C(16)
#define DN_ENTRY_HEADER_BYTES 40

static inline int dn_in_areas(size_t offset) {
    return (offset >= DN_ENTRY_BATCH_OFFSET && offset < DN_ENTRY_BATCH_OFFSET + DN_ENTRY_AREA) ||
           (offset >= DN_ENTRY_OUT_OFFSET && offset < DN_ENTRY_OUT_OFFSET + DN_ENTRY_AREA);
}

static inline void dn_fill_heap(void) {
    unsigned char *heap = cml_heap;
    for (size_t offset = DN_ENTRY_HEADER_BYTES; offset < DN_RUNTIME_SEGMENT_BYTES; offset += 8)
        memcpy(heap + offset, &(uint64_t){DN_ENTRY_FILL_WORD}, 8);
}

static inline int dn_fill_intact(void) {
    const unsigned char *heap = cml_heap;
    for (size_t offset = DN_ENTRY_HEADER_BYTES; offset < DN_RUNTIME_SEGMENT_BYTES; offset += 8) {
        uint64_t word;
        memcpy(&word, heap + offset, 8);
        if (!dn_in_areas(offset) && word != DN_ENTRY_FILL_WORD) return 0;
    }
    return 1;
}

/* Where the program found its heap header: checked on the first call, before the program could
   have written anything there. */
static inline void dn_header_checked(void) {
    static int checked;
    if (checked) return;
    checked = 1;
    if (!dn_runtime_header_intact())
        dn_fail("the heap header is not what the compiler theorem requires");
}
#endif
