/* SPDX-License-Identifier: AGPL-3.0-or-later
 * What the hosts of the entry benchmark share (scripts/entry_bench.py): failing with a reason,
 * strict numbers, the clock, words in memory, and the check that an array the program hands the
 * host lies in its heap. entry_layout.h is generated by that script. */
#ifndef DN_ENTRY_H
#define DN_ENTRY_H
#define _GNU_SOURCE
#include "cake_runtime.h"
#include "entry_layout.h"
#include <errno.h>
#include <inttypes.h>
#include <stdint.h>
#include <string.h>
#include <time.h>

/* The external functions the loop programs call; the generated code calls them as C functions. */
void ffidn_config(unsigned char *c, long clen, unsigned char *a, long alen);
void ffidn_nop(unsigned char *c, long clen, unsigned char *a, long alen);
void ffidn_next(unsigned char *c, long clen, unsigned char *a, long alen);
void ffidn_emit(unsigned char *c, long clen, unsigned char *a, long alen);

__attribute__((noreturn)) static inline void dn_fail(const char *what) {
    fprintf(stderr, "entry: %s\n", what);
    exit(1);
}

__attribute__((noreturn)) static inline void dn_fail_errno(const char *what) {
    fprintf(stderr, "entry: %s: %s\n", what, strerror(errno));
    exit(1);
}

/* A decimal number from `low` to `high`, or the process ends with the reason. */
static inline long dn_number(const char *text, long low, long high) {
    char *end;
    errno = 0;
    long value = strtol(text, &end, 10);
    if (errno || end == text || *end || value < low || value > high) {
        fprintf(stderr, "entry: '%s' is not a number from %ld to %ld\n", text, low, high);
        exit(2);
    }
    return value;
}

static inline double dn_now_ns(void) {
    struct timespec t;
    clock_gettime(CLOCK_MONOTONIC, &t);
    return (double)t.tv_sec * 1e9 + (double)t.tv_nsec;
}

static inline uint64_t dn_word(const unsigned char *p) {
    uint64_t value;
    memcpy(&value, p, sizeof value);
    return value;
}

static inline void dn_put_word(unsigned char *p, uint64_t value) { memcpy(p, &value, sizeof value); }

/* The theorem's domain is the heap from @base to @top, below the globals; these programs declare
   none, so it is the heap the runtime provisioned. */
static inline void dn_in_heap(const unsigned char *p, long len, const char *what) {
    uintptr_t start = (uintptr_t)cml_heap, end = start + DN_RUNTIME_SEGMENT_BYTES, at = (uintptr_t)p;
    if (len < 0 || at < start || at > end || (uintptr_t)len > end - at) {
        fprintf(stderr, "entry: %s: %ld bytes at %#" PRIxPTR " lie outside the heap [%#" PRIxPTR ", %#" PRIxPTR ")\n",
                what, len, at, start, end);
        exit(1);
    }
}

/* Everything in the heap past the header and outside the two batch areas is filled before a
   hostile or checked run and has to be untouched after it. The fill reads as a slot with a small
   length, so a program that strays out of its batch area finds plausible work there and gives
   itself away by answering it. */
#define DN_ENTRY_FILL_WORD UINT64_C(16)
#define DN_ENTRY_HEADER_BYTES 40

static inline int dn_in_areas(size_t offset) {
    return (offset >= DN_ENTRY_BATCH_OFFSET && offset < DN_ENTRY_BATCH_OFFSET + DN_ENTRY_AREA) ||
           (offset >= DN_ENTRY_OUT_OFFSET && offset < DN_ENTRY_OUT_OFFSET + DN_ENTRY_AREA);
}

static inline void dn_fill_heap(void) {
    unsigned char *heap = cml_heap;
    for (size_t offset = DN_ENTRY_HEADER_BYTES; offset < DN_RUNTIME_SEGMENT_BYTES; offset += 8)
        memcpy(heap + offset, &(uint64_t){DN_ENTRY_FILL_WORD}, 8);
}

static inline int dn_fill_intact(void) {
    const unsigned char *heap = cml_heap;
    for (size_t offset = DN_ENTRY_HEADER_BYTES; offset < DN_RUNTIME_SEGMENT_BYTES; offset += 8) {
        uint64_t word;
        memcpy(&word, heap + offset, 8);
        if (!dn_in_areas(offset) && word != DN_ENTRY_FILL_WORD) return 0;
    }
    return 1;
}

/* Where the program found its heap header: checked on the first call, before the program could
   have written anything there. */
static inline void dn_header_checked(void) {
    static int checked;
    if (checked) return;
    checked = 1;
    if (!dn_runtime_header_intact()) dn_fail("the heap header is not what the compiler theorem requires");
}
#endif
