#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Build the reply table into both entry designs, check them, and measure them.

The exported design is what the native lanes do: C runs the loop and calls `dn_reply`. The loop
design is what docs/decisions/0002-entry-and-memory.md chose: the program's `main` runs the loop
and fetches requests through external calls into its own heap. `check` builds both and runs the
correctness cases, including two variants that have to fail; `measure` checks first, then
measures and writes build/entry/report.json, where the decision's numbers come from.

The loop is Pancake written here rather than emitted: the emitter does not yet take calls or
external calls. It is built with `--main_return` so that `main` returning hands control back to
the clock; it exports nothing, so the runtime has no other entry to use.
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import platform
import select
import shutil
import statistics
import subprocess
import sys
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(Path(__file__).resolve().parent))
import native_baseline as baseline  # noqa: E402 - the path above is what makes it importable

OUT = ROOT / "build/entry"
NATIVE = ROOT / "native"
# The batch areas in the program's heap, from @base: one count word, then slots of a connection
# word, a length word and the data. The Pancake program and the C header are both written from
# these, so they cannot disagree.
BATCH_OFFSET = 64
OUT_OFFSET = 8192
DATA = 72
SLOT = 16 + DATA
BATCH_MAX = 64
AREA = 8 + BATCH_MAX * SLOT
# The commands the hosts send; the replies they expect come from the reference in native_baseline.
COMMANDS = (b"QUIT\r\n", b"MODE READER\r\n", b"HELP\r\n", b"LIST\r\n", b"QUITTING\r\n",
            b"MODE READ\r\n", baseline.BINARY_KEYWORD + b"x")

NOP_MAIN = """
fun main() {
  @dn_config(@base, 0, @base + 64, 8);
  var n = lds 1 (@base + 64);
  var i = 0;
  while i < n {
    @dn_nop(@base, 0, @base + 64, 8);
    i = i + 1;
  }
  return 0;
}
"""


# The checks the loop makes on what the host writes, each named so that a variant can leave out
# exactly one of them, and the hostile case of entry_micro_loop.c that only it stops.
HOST_CHECKS = {"count_negative": ("k < 0", "2"), "count_max": (f"{BATCH_MAX} < k", "1"),
               "length_negative": ("n < 0", "4"), "length_max": (f"{DATA} < n", "3")}


def loop_main(omit: str | None = None, next_array: str = "batch") -> str:
    """The server loop. It checks every count and length the host writes before using it, so that
    no host can make it read or write outside its batch areas. `omit` leaves out one of those
    checks, and `next_array` moves the array it hands the host, for the variants `check` refuses."""
    def guard(name: str, indent: str) -> str:
        condition = HOST_CHECKS[name][0]
        return "" if name == omit else f"{indent}if {condition} {{\n{indent}  return 1;\n{indent}}}\n"

    return f"""
fun main() {{
  var batch = @base + {BATCH_OFFSET};
  var out = @base + {OUT_OFFSET};
  var going = 1;
  while going {{
    @dn_next(@base, 0, {next_array}, {AREA});
    var k = lds 1 batch;
{guard("count_negative", "    ")}{guard("count_max", "    ")}    if k == 0 {{
      going = 0;
    }} else {{
      var i = 0;
      while i < k {{
        var slot = batch + 8 + (i * {SLOT});
        var reply = out + 8 + (i * {SLOT});
        var n = lds 1 (slot + 8);
{guard("length_negative", "        ")}{guard("length_max", "        ")}        st reply, lds 1 slot;
        var r = dn_reply(slot + 16, n, reply + 16, {DATA});
        st reply + 8, r;
        i = i + 1;
      }}
      st out, k;
      @dn_emit(@base, 0, out, {AREA});
    }}
  }}
  return 0;
}}
"""


def layout_header() -> str:
    """The C side of the layout, and the commands with the replies the reference gives them."""
    def array(name: str, data: bytes) -> str:
        return f"static const unsigned char {name}[] = {{{', '.join(str(b) for b in data) or '0'}}};\n"

    lines = ["/* Generated by scripts/entry_bench.py. */\n", "#ifndef DN_ENTRY_LAYOUT_H\n",
             "#define DN_ENTRY_LAYOUT_H\n"]
    for name, value in (("BATCH_OFFSET", BATCH_OFFSET), ("OUT_OFFSET", OUT_OFFSET), ("DATA", DATA),
                        ("SLOT", SLOT), ("BATCH_MAX", BATCH_MAX), ("AREA", AREA), ("COMMANDS", len(COMMANDS))):
        lines.append(f"#define DN_ENTRY_{name} {value}\n")
    replies = [baseline.reply(command) for command in COMMANDS]
    for i, (command, answer) in enumerate(zip(COMMANDS, replies, strict=True)):
        if len(command) > DATA or len(answer) > DATA:
            raise RuntimeError(f"command {i} or its reply does not fit a slot")
        lines += [array(f"dn_entry_command_{i}", command), array(f"dn_entry_reply_{i}", answer)]
    count = range(len(COMMANDS))
    lines.append("static const unsigned char *const dn_entry_commands[] = {"
                 + ", ".join(f"dn_entry_command_{i}" for i in count) + "};\n")
    lines.append("static const long dn_entry_command_lengths[] = {"
                 + ", ".join(str(len(c)) for c in COMMANDS) + "};\n")
    lines.append("static const unsigned char *const dn_entry_replies[] = {"
                 + ", ".join(f"dn_entry_reply_{i}" for i in count) + "};\n")
    lines.append("static const long dn_entry_reply_lengths[] = {"
                 + ", ".join(str(len(r)) for r in replies) + "};\n")
    lines.append("#endif\n")
    return "".join(lines)


def compile_program(cake: str, name: str, source: str) -> Path:
    """Compile a Pancake program; any diagnostic fails, and `cake_bitmaps` is made global so that
    the host can write the heap header (native/cake_header.c)."""
    pnk, asm = OUT / f"{name}.pnk", OUT / f"{name}.S"
    pnk.write_text(source)
    with pnk.open("rb") as inp, asm.open("wb") as output:
        done = subprocess.run([cake, "--pancake", "--main_return=true"], stdin=inp, stdout=output,
                              stderr=subprocess.PIPE, timeout=300, check=False)
    if done.returncode or done.stderr:
        raise RuntimeError(f"{name}.pnk compiled with diagnostics:\n{done.stderr.decode(errors='replace')}")
    # The namespace check reads the assembly as the compiler wrote it; the one symbol added after
    # it is the bitmaps label, which changes no instruction.
    baseline.check_symbols(asm, OUT / f"{name}.o")
    text = asm.read_text()
    if text.count("\ncake_bitmaps:\n") != 1:
        raise RuntimeError(f"{name}.S: the bitmaps label is not where the host expects it")
    asm.write_text(text.replace("\ncake_bitmaps:\n", "\n     .globl cake_bitmaps\ncake_bitmaps:\n"))
    return asm


def link(name: str, sources: list[Path]) -> Path:
    binary = OUT / name
    baseline.loud([os.environ.get("CC", "cc"), *baseline.HARDENING, "-I", str(NATIVE), "-I", str(NATIVE / "entry"),
                   "-I", str(OUT), *map(str, sources), "-o", str(binary)], timeout=120, what=f"linking {name}")
    baseline.hardened(binary)
    return binary


def build(cake: str) -> dict[str, Path]:
    """Compile every program and link every host; returns the assembly of each program."""
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "entry_layout.h").write_text(layout_header())
    compiler = ROOT / ".lake/build/bin/dn-compiler"
    reply = baseline.loud([str(compiler), "emit-reply"], timeout=60, what="emitting dn_reply")
    if reply.count("export fun dn_reply") != 1 or reply.count("st8 out + pos + 0, 50;") < 1:
        raise RuntimeError("the emitted reply table is not the one this benchmark was written against")
    internal = reply.replace("export fun dn_reply", "fun dn_reply")
    nop = "\nexport fun dn_nop(1 a) {\n  return a + 1;\n}\n"
    programs = {
        "export": reply + nop,
        # the first reply byte changed from '2' to '3', for the client to refuse
        "export-wrong": reply.replace("st8 out + pos + 0, 50;", "st8 out + pos + 0, 51;", 1) + nop,
        "loop": internal + loop_main(),
        # the array handed to the host moved past the end of the heap, for the host to refuse
        "loop-misplaced": internal + loop_main(next_array="@base + 2000000"),
        "loop-nop": NOP_MAIN,
        **{f"loop-without-{name}": internal + loop_main(omit=name) for name in HOST_CHECKS},
    }
    asm = {name: compile_program(cake, name, source) for name, source in programs.items()}
    runtime = [NATIVE / "cake_runtime.c", NATIVE / "cake_header.c"]
    entry = NATIVE / "entry"
    link("micro-export", [entry / "entry_micro_export.c", *runtime, asm["export"]])
    for name in ("loop", "loop-misplaced", "loop-nop", *(f"loop-without-{n}" for n in HOST_CHECKS)):
        link(f"micro-{name}", [entry / "entry_micro_loop.c", *runtime, asm[name]])
    link("server-export", [entry / "entry_server_export.c", *runtime, asm["export"]])
    link("server-export-wrong", [entry / "entry_server_export.c", *runtime, asm["export-wrong"]])
    link("server-loop", [entry / "entry_server_loop.c", *runtime, asm["loop"]])
    link("client", [entry / "entry_client.c"])
    return asm


def listed_values(text: str, label: str, directive: str) -> int:
    """How many values the `directive` lines right after `label` list, up to the next other line."""
    lines = text.splitlines()
    if lines.count(label) != 1:
        raise RuntimeError(f"the assembly does not have exactly one {label}")
    count = 0
    for line in lines[lines.index(label) + 1:]:
        stripped = line.strip()
        if not stripped or stripped.startswith("/*"):
            continue
        if not stripped.startswith(directive + " "):
            break
        count += len(stripped[len(directive):].split(","))
    return count


def expected_header(asm: Path, binary: Path) -> list[int]:
    """The five words pan_installed requires, worked out from the assembly and the linked symbols
    rather than from the table cake_header.c writes, relative to cake_text_begin. The bitmaps are
    followed by a data buffer, and the machine code by a code buffer; both buffers are whatever
    lies between their labels, which the theorem leaves free."""
    text = asm.read_text()
    listing = baseline.loud(["nm", str(binary)], timeout=60, what=f"reading symbols of {binary.name}")
    symbols = {parts[2]: int(parts[0], 16) for line in listing.splitlines() if len(parts := line.split()) == 3}
    at = {name: symbols[name] - symbols["cake_text_begin"] for name in
          ("cake_bitmaps", "cake_bitmaps_buffer_begin", "cake_bitmaps_buffer_end", "cake_main",
           "cake_codebuffer_begin", "cake_codebuffer_end")}
    data = at["cake_bitmaps"] + 8 * listed_values(text, "cake_bitmaps:", ".quad")
    code = at["cake_main"] + listed_values(text, "cake_main:", ".byte")
    data_end, code_end = at["cake_bitmaps_buffer_end"], at["cake_codebuffer_end"]
    if data != at["cake_bitmaps_buffer_begin"] or code != at["cake_codebuffer_begin"]:
        raise RuntimeError("the buffers do not begin where the bitmaps and the machine code end")
    if data_end < data or (data_end - data) % 8 or code_end < code:
        raise RuntimeError("a buffer ends before it begins")
    return [at["cake_bitmaps"], data, data_end, code, code_end]


def pinned(cpu: int | None) -> list[str]:
    return ["taskset", "-c", str(cpu)] if cpu is not None else []


def run(args: list[str], cpu: int | None = None, timeout: int = 120) -> dict[str, Any]:
    done = subprocess.run([*pinned(cpu), str(OUT / args[0]), *args[1:]], capture_output=True, text=True,
                          timeout=timeout, check=False)
    if done.returncode:
        raise RuntimeError(f"{' '.join(args)} failed with status {done.returncode}:\n{done.stderr}")
    result: dict[str, Any] = json.loads(done.stdout)
    return result


def refused(args: list[str], status: int | None, message: str) -> None:
    """A variant that breaks one property has to fail on it: the check is seen red."""
    done = subprocess.run([str(OUT / args[0]), *args[1:]], capture_output=True, text=True, timeout=120, check=False)
    if done.returncode == 0 or (status is not None and done.returncode != status) or message not in done.stderr:
        raise RuntimeError(f"{' '.join(args)} was not refused as it should be (status {done.returncode}):\n"
                           f"{done.stdout}{done.stderr}")


def serve(server: list[str], connections: int, each: int, cpus: tuple[int | None, int | None],
          timeout: int) -> tuple[subprocess.CompletedProcess[str], int, str]:
    """Start the server, run the client against it, and return the client's run with the server's
    status and error output. The server is killed if it outlives the client."""
    process = subprocess.Popen([*pinned(cpus[0]), str(OUT / server[0]), str(connections * each), *server[1:]],
                               stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    try:
        ready, _, _ = select.select([process.stdout], [], [], 30) if process.stdout else ([], [], [])
        port = process.stdout.readline().strip() if ready and process.stdout else ""
        if not port:
            raise RuntimeError(f"{server[0]} did not say which port it listens on")
        client = subprocess.run([*pinned(cpus[1]), str(OUT / "client"), port, str(connections), str(each)],
                                capture_output=True, text=True, timeout=timeout, check=False)
        try:
            _, errors = process.communicate(timeout=30 if client.returncode == 0 else 1)
        except subprocess.TimeoutExpired:
            errors = "the server did not finish"
    finally:
        if process.poll() is None:
            process.kill()
            process.wait()
    return client, process.returncode, errors


def network(server: list[str], connections: int, each: int, cpus: tuple[int | None, int | None],
            timeout: int = 120) -> float:
    client, status, errors = serve(server, connections, each, cpus, timeout)
    if client.returncode or status:
        raise RuntimeError(f"{' '.join(server)} with {connections} connections: client {client.returncode} "
                           f"{client.stderr} server {status} {errors}")
    rate: float = json.loads(client.stdout)["requests_per_second"]
    return rate


SERVERS = {"export": ["server-export"], "loop_batch64": ["server-loop", "64"], "loop_batch1": ["server-loop", "1"],
           "loop_batch1_repoll": ["server-loop", "1", "--repoll"]}


def check(asm: dict[str, Path]) -> dict[str, int]:
    """What the decision rests on, each part also shown failing: every reply right in both
    designs; nothing written outside the batch areas; the heap header as pan_installed requires,
    recomputed from the assembly; a hostile host stopped by each of the loop's checks, and refused
    without it; an array outside the heap, a missing header and a wrong reply refused. Returns how
    many of each ran."""
    replies = [["micro-export", "reply", "20000"], ["micro-export", "nop", "100000"],
               ["micro-loop", "reply", "20000", "1"], ["micro-loop", "reply", "20000", "64"],
               ["micro-loop-nop", "nop", "100000"]]
    for args in replies:
        run(args)
    written = run(["micro-loop", "header"])["header"]
    if written != expected_header(asm["loop"], OUT / "micro-loop"):
        raise RuntimeError(f"the heap header written is not the one pan_installed requires: {written}")
    for name, (_, case) in HOST_CHECKS.items():
        if run(["micro-loop", "hostile", case])["stopped"] is not True:
            raise RuntimeError(f"hostile case {case} was not stopped")
        message = "outside its batch areas" if name == "count_max" else "answered a hostile batch"
        refused([f"micro-loop-without-{name}", "hostile", case], 1, message)
    variants = [(["micro-loop-misplaced", "reply", "100", "8"], "outside the heap"),
                (["micro-loop", "reply", "1000", "8", "--no-header"], "heap header")]
    for args, message in variants:
        refused(args, 1, message)
    for server in SERVERS.values():
        network(server, 8, 500, (None, None))
    client, _, _ = serve(["server-export-wrong"], 1, 10, (None, None), 60)
    if client.returncode == 0 or "not the one the reference gives" not in client.stderr:
        raise RuntimeError(f"the client took a wrong reply:\n{client.stdout}{client.stderr}")
    return {"reply_runs": len(replies), "header_words": len(written), "hostile_cases": len(HOST_CHECKS),
            "refused_variants": len(HOST_CHECKS) + len(variants) + 1, "network_servers": len(SERVERS)}


def spread(samples: list[float]) -> dict[str, float]:
    if not samples or min(samples) <= 0:
        raise RuntimeError(f"a measurement came out empty or non-positive: {samples}")
    return {"median": statistics.median(samples), "min": min(samples), "max": max(samples)}


def processor() -> str:
    for line in Path("/proc/cpuinfo").read_text().splitlines():
        if line.startswith("model name"):
            return line.split(":", 1)[1].strip()
    return platform.processor()


def core_of(cpu: int) -> str | None:
    topology = Path(f"/sys/devices/system/cpu/cpu{cpu}/topology")
    try:
        package = (topology / "physical_package_id").read_text().strip()
        core = (topology / "core_id").read_text().strip()
    except OSError:
        return None
    return f"{package}:{core}"


def separate_cpus() -> tuple[int | None, int | None]:
    """Two processors on different physical cores, leaving the first core to the system when
    there are enough; a sibling thread would share the core it is meant to leave alone."""
    if not shutil.which("taskset"):
        return (None, None)
    first: dict[str, int] = {}
    for cpu in sorted(os.sched_getaffinity(0)):
        core = core_of(cpu)
        if core is None:
            return (None, None)
        first.setdefault(core, cpu)
    cores = list(first.values())
    if len(cores) > 2:
        cores = cores[1:]
    return (cores[0], cores[1]) if len(cores) >= 2 else (None, None)


def read(path: Path) -> str | None:
    try:
        return path.read_text().strip()
    except OSError:
        return None


def machine(cpus: tuple[int | None, int | None]) -> dict[str, Any]:
    """What the numbers depend on beyond the code: the processor, its frequency policy, the C
    compiler, the revision measured, and which threads share a core with the pinned ones."""
    compiler = baseline.loud([os.environ.get("CC", "cc"), "--version"], timeout=30, what="asking the C compiler")
    revision = subprocess.run(["git", "-C", str(ROOT), "rev-parse", "HEAD"], capture_output=True, text=True,
                              timeout=30, check=False).stdout.strip()
    changed = subprocess.run(["git", "--no-optional-locks", "-C", str(ROOT), "status", "--porcelain"],
                             capture_output=True, text=True, timeout=30, check=False).stdout
    system = Path("/sys/devices/system/cpu")
    return {"processor": processor(), "governor": read(system / "cpu0/cpufreq/scaling_governor"),
            "boost": read(system / "cpufreq/boost"), "c_compiler": compiler.splitlines()[0],
            "revision": revision or None, "uncommitted_changes": bool(changed),
            "pinned_cpus": list(cpus),
            "core_siblings": [read(system / f"cpu{cpu}/topology/thread_siblings_list") for cpu in cpus
                              if cpu is not None]}


def measure() -> dict[str, Any]:
    load_before = os.getloadavg()
    cpus = separate_cpus()
    micro: dict[str, Any] = {}
    network_rates: dict[str, Any] = {}
    micro_runs: dict[str, list[str]] = {
        "export_nop_ns": ["micro-export", "nop", "20000000"],
        "loop_nop_ns": ["micro-loop-nop", "nop", "20000000"],
        "export_reply_ns": ["micro-export", "reply", "5000000"],
        **{f"loop_reply_batch{k}_ns": ["micro-loop", "reply", "5000000", str(k)] for k in (1, 8, 16, 64)},
    }
    for label, args in micro_runs.items():
        key = "ns_per_call" if "nop" in label else "ns_per_event"
        run(args, cpus[0], 900)
        micro[label] = spread([float(run(args, cpus[0], 900)[key]) for _ in range(5)])
    for connections, each in ((1, 50000), (32, 5000), (128, 1500)):
        for label, server in SERVERS.items():
            network(server, connections, each, cpus, 900)
            network_rates[f"{label}_{connections}_rps"] = spread(
                [network(server, connections, each, cpus, 900) for _ in range(3)])
    return {"micro": micro, "network": network_rates, "machine": machine(cpus),
            "load_average_before": list(load_before), "load_average_after": list(os.getloadavg())}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mode", choices=("check", "measure"))
    parser.add_argument("--cake", default=os.environ.get("CAKE"))
    parser.add_argument("--busy", action="store_true",
                        help="measure even while other work loads the machine; the report records the load")
    args = parser.parse_args()
    if platform.system() != "Linux" or platform.machine() != "x86_64":
        parser.error("the entry benchmark runs on Linux x86-64")
    cake = shutil.which(args.cake or "")
    if not cake:
        parser.error("provide --cake or CAKE")
    # Other work on the machine moves every number here, so a measurement starts only on a quiet
    # machine unless asked otherwise, and the report says how loaded it was either way.
    load = os.getloadavg()[0]
    if args.mode == "measure" and not args.busy and load > (os.cpu_count() or 1) / 8:
        parser.error(f"the one-minute load average is {load:.1f}; measure on a quiet machine or pass --busy")
    report_path = OUT / "report.json"
    report_path.unlink(missing_ok=True)
    asm = build(cake)
    report: dict[str, Any] = {"status": "checked", "checks": check(asm), "compiler_sha256": baseline.digest(cake),
                              "platform": platform.platform(), "cpus": os.cpu_count()}
    if args.mode == "measure":
        report.update(status="measured", **measure())
    report_path.write_text(json.dumps(report, indent=2) + "\n")
    print(report_path.read_text(), end="")


if __name__ == "__main__":
    main()
