#!/usr/bin/env python3
"""Generate the Pancake keyword table from the lexers of the pinned revisions.

`Checked.identifier` may not accept a word the lexer turns into a keyword, so the table
is taken from `get_keyword_def` itself rather than written by hand. The generated file is
committed; `--check` refetches the lexers and fails if it is out of date. Needs network.
"""
from __future__ import annotations

import argparse
from collections.abc import Callable
import hashlib
import json
from pathlib import Path
import re
import subprocess
import sys
import textwrap

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "lean/DN/Compiler/Keywords.lean"
REPOSITORIES = {"cakeml": "CakeML/cakeml", "hol": "HOL-Theorem-Prover/HOL"}
KEYWORD = re.compile(r'if s = "([^"]*)" then')
NAME = re.compile(r"[A-Za-z_][A-Za-z0-9_]*\Z")
# Words every Pancake lexer has: if they are missing, the definition changed shape and the
# table would be silently short.
EXPECTED = {"if", "else", "while", "return", "var", "skip"}
HEADER = """/-
Generated by scripts/gen_keywords.py from the Pancake lexers of the pinned revisions.
Do not edit by hand.
-/
namespace DN.Compiler.Keywords

/-- The words `get_keyword_def` turns into keywords, per pinned revision. Words with a
leading `@` and the empty string are left out: the identifier rule rejects them by shape. -/
def byRevision : List (String \u00d7 List String) :=
"""
FOOTER = """
/-- Every word that is a keyword at some pinned revision. -/
def all : List String := (byRevision.flatMap Prod.snd).eraseDups

end DN.Compiler.Keywords
"""


def fetch(source: dict[str, str]) -> bytes:
    url = (f"https://raw.githubusercontent.com/{REPOSITORIES[source['component']]}/"
           f"{source['revision']}/{source['path']}")
    content = subprocess.run(["curl", "--proto", "=https", "--tlsv1.2", "--fail", "--location",
                              "--retry", "3", "--connect-timeout", "20", "--max-time", "120",
                              "--silent", "--show-error", url],
                             capture_output=True, check=True).stdout
    digest = hashlib.sha256(content).hexdigest()
    if digest != source["sha256"]:
        raise SystemExit(f"{source['path']} at {source['revision'][:7]}: {digest} recorded as "
                         f"{source['sha256']}")
    return content


def keywords_of(lexer: str) -> list[str]:
    body = lexer.partition("Definition get_keyword_def:")[2].partition("\nEnd")[0]
    if not body:
        raise SystemExit("get_keyword_def not found: the lexer moved")
    words = [word for word in KEYWORD.findall(body) if word and not word.startswith("@")]
    stray = [word for word in words if not NAME.match(word)]
    if stray:
        raise SystemExit(f"keywords that are not plain names: {stray}")
    missing = EXPECTED - set(words)
    if missing:
        raise SystemExit(f"get_keyword_def yielded no {sorted(missing)}: the definition changed shape")
    return words


def render(sources: list[dict[str, str]],
           get: Callable[[dict[str, str]], bytes] = fetch) -> str:
    if not sources:
        raise SystemExit("backend/lock.json records no lexer source")
    entries = []
    for source in sources:
        quoted = [f'"{word}"' for word in keywords_of(get(source).decode())]
        words = textwrap.fill(", ".join(quoted), width=92, initial_indent="    [",
                              subsequent_indent="     ", break_long_words=False)
        entries.append(f'   ("{source["revision"]}",\n{words}])')
    return HEADER + "  [" + ",\n".join(entries).lstrip() + "]\n" + FOOTER


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="fail if the committed table differs from the pinned lexers")
    arguments = parser.parse_args()
    sources = json.loads((ROOT / "backend/lock.json").read_text())["lexer_sources"]
    generated = render(sources)
    if not arguments.check:
        TARGET.write_text(generated)
        print(f"wrote {TARGET.relative_to(ROOT)}")
        return
    if TARGET.read_text() != generated:
        sys.exit(f"{TARGET.relative_to(ROOT)} is out of date: rerun scripts/gen_keywords.py")
    print(f"keywords: {TARGET.relative_to(ROOT)} matches the pinned lexers")


if __name__ == "__main__":
    main()
